# Generated by Django 4.2.2 on 2023-06-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Brands', 'verbose_name_plural': 'Brands'},
        ),
    ]
