# Generated by Django 4.2.2 on 2023-06-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_charge',
            new_name='delivery_fee',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='mobile_no',
        ),
    ]
