# Generated by Django 4.2.2 on 2023-06-20 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0002_alter_brands_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('products_description', models.TextField(blank=True)),
                ('actual_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('trending', models.BooleanField(default=False, help_text='1:show,0:hide')),
                ('stock', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='photos/products')),
                ('ram', models.CharField(max_length=10)),
                ('storage', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brands')),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
