# Generated by Django 4.2.2 on 2023-06-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='connectivity',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
