# Generated by Django 4.2.2 on 2023-06-20 13:10

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_products_connectivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='products_description',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True)),
        ),
    ]
