# Generated by Django 4.2.2 on 2023-06-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_products_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='products_description',
            field=models.TextField(blank=True),
        ),
    ]
