# Generated by Django 4.2.2 on 2023-06-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
